// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <dtsOsgCal/IOUtils>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_VALUE_REFLECTOR(dtsOsgCal::VBOs)
	I_ConstructorWithDefaults2(IN, int, maxVertices, OSGCAL_MAX_VERTEX_PER_MODEL, IN, int, maxFaces, OSGCAL_MAX_VERTEX_PER_MODEL *3);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::VertexBuffer >, vertexBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::WeightBuffer >, weightBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::MatrixIndexBuffer >, matrixIndexBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::NormalBuffer >, normalBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::TangentBuffer >, tangentBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::BinormalBuffer >, binormalBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::TexCoordBuffer >, texCoordBuffer);
	I_PublicMemberProperty(osg::ref_ptr< dtsOsgCal::IndexBuffer >, indexBuffer);
	I_PublicMemberProperty(int, vertexCount);
	I_PublicMemberProperty(int, faceCount);
END_REFLECTOR

TYPE_NAME_ALIAS(osg::Vec3Array, dtsOsgCal::VertexBuffer);

TYPE_NAME_ALIAS(osg::Vec4Array, dtsOsgCal::WeightBuffer);

TYPE_NAME_ALIAS(osg::Vec4sArray, dtsOsgCal::MatrixIndexBuffer);

TYPE_NAME_ALIAS(osg::Vec3Array, dtsOsgCal::NormalBuffer);

TYPE_NAME_ALIAS(osg::Vec3Array, dtsOsgCal::TangentBuffer);

TYPE_NAME_ALIAS(osg::Vec3Array, dtsOsgCal::BinormalBuffer);

TYPE_NAME_ALIAS(osg::Vec2Array, dtsOsgCal::TexCoordBuffer);

TYPE_NAME_ALIAS(osg::UIntArray, dtsOsgCal::IndexBuffer);

