// ***************************************************************************
//
//   Generated automatically by genwrapper.
//   Please DO NOT EDIT this file!
//
// ***************************************************************************

#include <osgIntrospection/ReflectionMacros>
#include <osgIntrospection/TypedMethodInfo>
#include <osgIntrospection/StaticMethodInfo>
#include <osgIntrospection/Attributes>

#include <dtsOsgCal/CoreModel>
#include <dtsOsgCal/IOUtils>
#include <dtsOsgCal/Model>

// Must undefine IN and OUT macros defined in Windows headers
#ifdef IN
#undef IN
#endif
#ifdef OUT
#undef OUT
#endif

BEGIN_OBJECT_REFLECTOR(dtsOsgCal::AllMeshes)
	I_BaseType(dtsOsgCal::MeshFilter);
	I_Constructor0();
	I_Method1(bool, filter, IN, const dtsOsgCal::CoreModel::Mesh &, mesh);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(dtsOsgCal::AllMeshesHardware)
	I_BaseType(dtsOsgCal::MeshTyper);
	I_Constructor0();
	I_Method1(dtsOsgCal::MeshType, type, IN, const dtsOsgCal::CoreModel::Mesh &, mesh);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(dtsOsgCal::AllMeshesSoftware)
	I_BaseType(dtsOsgCal::MeshTyper);
	I_Constructor0();
	I_Method1(dtsOsgCal::MeshType, type, IN, const dtsOsgCal::CoreModel::Mesh &, mesh);
END_REFLECTOR

BEGIN_ABSTRACT_OBJECT_REFLECTOR(dtsOsgCal::MeshFilter)
	I_Constructor0();
	I_Method1(bool, filter, IN, const dtsOsgCal::CoreModel::Mesh &, mesh);
END_REFLECTOR

BEGIN_ABSTRACT_OBJECT_REFLECTOR(dtsOsgCal::MeshTyper)
	I_Constructor0();
	I_Method1(dtsOsgCal::MeshType, type, IN, const dtsOsgCal::CoreModel::Mesh &, mesh);
END_REFLECTOR

TYPE_NAME_ALIAS(osg::ByteArray, dtsOsgCal::Model::UpdateFlagBuffer);

BEGIN_OBJECT_REFLECTOR(dtsOsgCal::Model)
	I_Constructor0();
	I_MethodWithDefaults3(void, load, IN, dtsOsgCal::CoreModel *, coreModel, , IN, dtsOsgCal::MeshTyper *, meshTyper, 0, IN, dtsOsgCal::MeshFilter *, meshFilter, 0);
	I_Method0(void, update);
	I_Method0(CalModel *, getCalModel);
	I_Method0(dtsOsgCal::CoreModel *, getCoreModel);
	I_Method0(dtsOsgCal::VertexBuffer *, getVertexBuffer);
	I_Method0(dtsOsgCal::NormalBuffer *, getNormalBuffer);
	I_Method0(dtsOsgCal::Model::UpdateFlagBuffer *, getUpdateFlagBuffer);
	I_Method3(void, blendCycle, IN, int, id, IN, float, weight, IN, float, delay);
	I_Method2(void, clearCycle, IN, int, id, IN, float, delay);
	I_Method1(osg::Geometry *, getMesh, IN, const std::string &, name);
	I_ReadOnlyProperty(CalModel *, CalModel);
	I_ReadOnlyProperty(dtsOsgCal::CoreModel *, CoreModel);
	I_ReadOnlyProperty(dtsOsgCal::NormalBuffer *, NormalBuffer);
	I_ReadOnlyProperty(dtsOsgCal::Model::UpdateFlagBuffer *, UpdateFlagBuffer);
	I_ReadOnlyProperty(dtsOsgCal::VertexBuffer *, VertexBuffer);
END_REFLECTOR

BEGIN_OBJECT_REFLECTOR(dtsOsgCal::OneMesh)
	I_BaseType(dtsOsgCal::MeshFilter);
	I_Constructor1(IN, const std::string &, mn);
	I_Method1(bool, filter, IN, const dtsOsgCal::CoreModel::Mesh &, mesh);
	I_PublicMemberProperty(std::string, meshName);
END_REFLECTOR

BEGIN_ENUM_REFLECTOR(dtsOsgCal::MeshType)
	I_EnumLabel(dtsOsgCal::MT_HARDWARE);
	I_EnumLabel(dtsOsgCal::MT_SOFTWARE);
END_REFLECTOR

